### ISSUE TITLE
Does not work with replacements

### ISSUE THREAD

**Issue by andremarianiello** [goware/modvendor#1]
if you replace a module with another module, modvendor complains that it can't find the original module path, but it should be looking for the replacing module path

**Comment by andremarianiello** [comment]
I think 

```diff
diff --git a/main.go b/main.go
index 69f63c1..7c76c10 100644
--- a/main.go
+++ b/main.go
@@ -71,8 +71,8 @@ func main() {
                        s := strings.Split(line, " ")

                        mod = &Mod{
-                               ImportPath: s[1],
-                               Version:    s[2],
+                               ImportPath: s[len(s)-2],
+                               Version:    s[len(s)-1],
                        }
                        mod.Dir = pkgModPath(mod.ImportPath, mod.Version)
```

fixes this issue btw

**Comment by pkieltyka** [comment]
oh thanks, just seeing this issue.. I haven't come across this bug yet, but when I do I'll make sure to try this fix -- thank you. If anyone else runs into it, pls let us kno

**Comment by yutongp** [comment]
I ran into same issue:
```
modvendor -copy="**/*.c **/*.h **/*.proto" -v
Error! $GOPATH/pkg/mod/github.com/ethereum/go-ethereum@v1.8.23 module path does not exist, check $GOPATH/pkg/mod
```
here is the go.mod part
```
require (
	github.com/ethereum/go-ethereum v1.8.23
)

replace github.com/ethereum/go-ethereum v1.8.23 => github.com/iotexproject/go-ethereum v1.7.4-0.20190216004546-2bbee71fbe61
```

here is the `vendor/modules.txt` part:
```
# github.com/ethereum/go-ethereum v1.8.23 => github.com/iotexproject/go-ethereum v1.7.4-0.20190216004546-2bbee71fbe61
```

**Comment by EVODelavega** [comment]
Hi, I've taken the liberty to open a PR with a fix here: https://github.com/goware/modvendor/pull/2

Perhaps just using relative indexes on the `s` slice would've been enough, as suggested above, but I hadn't spotted this issue before I made the changes. I tested them locally, and everything worked just fine
