### ISSUE TITLE
panic: replace directive can point to a local path without version

### ISSUE THREAD

**Issue by benma** [goware/modvendor#12]
in https://github.com/goware/modvendor/blob/892bf4ecb805b052575eb45070a60f9db471df8e/main.go#L86, the code assumes that the replacement is a go package with a version.

However it could also be a local path, like `replace github.com/some/package v1.2.3 => /opt/some/package`. In this case, this tool panics.

**Comment by pedropombeiro** [comment]
I also ran into this, but then realized that modvendor doesn't seem to be necessary anymore with Go 1.13 for my usage scenarion (copying .c and .h files)

**Comment by pkieltyka** [comment]
@pedropombeiro how do you vendor .c and .h files now? would be great if there was no need for modvendor, is this possible in latest go toolchain?

**Comment by pedropombeiro** [comment]
Pinging @adambabik

**Comment by adambabik** [comment]
@pedropombeiro How do you vendor `*.{c,h}` files in Go 1.13? I haven't seen any changes to `go mod -vendor` in that area, we still use this project even after migrating to 1.13.

**Comment by pkieltyka** [comment]
hmm.. I vendor .c and .h files in Go 1.13 and 1.14 via: `go run github.com/goware/modvendor -copy="**/*.c **/*.h **/*.s **/*.proto"`

**Comment by pedropombeiro** [comment]
I'm not currently using modvendor, so I have no input here.
