### ISSUE TITLE
modvendor does not handle uppercase letters in versions strings

### ISSUE THREAD

**Issue by mx-psi** [goware/modvendor#25]
Take the following `main.go` file

```go
package main

import (
	_ "go.opentelemetry.io/otel"
)
```

with the following `go.mod` file:

```
module example.com/modvendor

go 1.16

require go.opentelemetry.io/otel v1.0.0-RC3
```

This will make `modvendor` fail:
```
❯ go mod vendor

❯ modvendor -copy="**/*.c **/*.h **/*.proto **/*.java"
Error! "<GOPATH goes here>/pkg/mod/go.opentelemetry.io/otel@v1.0.0-RC3" module path does not exist, check $GOPATH/pkg/mod
```

since the `pkgModPath` version handles uppercase letters correctly on the module path but not on the version.

**Comment by pkieltyka** [comment]
thx, https://github.com/goware/modvendor/tree/v0.5.0

**Comment by mx-psi** [comment]
Thank you very much for the extremely quick release :)
