### ISSUE TITLE
new replace directive breaks modvendor

### ISSUE THREAD

**Issue by kevinburke1** [goware/modvendor#9]
Found a second error... `modvendor` was trying to parse the `replace` directives to figure out when it needed to get a new module path for a directory. It did so by checking if the fourth token on a line was `=>`.

The last line in the modules.txt file - a replace directive - has the arrow as the third token so this now fails.

```
# github.com/goware/modvendor => github.com/meterup/modvendor v0.0.0-20191010172136-c2d7e3539f83
```

```
			// Handle "replace" in module file if any
			if len(s) > 3 && s[3] == "=>" {
				mod.SourcePath = s[4]
				mod.SourceVersion = s[5]
				mod.Dir = pkgModPath(mod.SourcePath, mod.SourceVersion)
			} else {
				mod.Dir = pkgModPath(mod.ImportPath, mod.Version)
			}

			if _, err := os.Stat(mod.Dir); os.IsNotExist(err) {
				fmt.Printf("Error! %q module path does not exist, check $GOPATH/pkg/mod\n", mod.Dir)
				os.Exit(1)
			}
```

I'm a little confused because my `vendor/modules.txt` also has this about halfway through the file:

```
# github.com/goware/modvendor v0.0.0-20190516042800-ce72b408a8fe => github.com/meterup/modvendor v0.0.0-20191010172136-c2d7e3539f83
```

I'm not sure which one takes precedence.

**Comment by pkieltyka** [comment]
done via https://github.com/goware/modvendor/pull/10
